build:
    environment:
        php:
            version: '7.4'
    tests:
        override:
            -
                command: 'vendor/bin/codecept run --coverage --coverage-xml'
                coverage:
                    file: 'tests/_output/coverage.xml'
                    format: 'clover'